---
- hosts: localhost
  tasks:
    - name: configure ipv4 dhcp fixed address
      nios_fixed_address:
        name: ipv4_fixed
        ipaddr: '{{ ipaddr }}'
        mac: '{{ mac }}'
        network: '{{ network }}'
        network_view: '{{ network_view }}'
        comment: '{{ comment }}'
        state: '{{ state }}'
        provider:
          host: 172.17.20.50
          username: admin
          password: infoblox
      connection: local
