---
- hosts: localhost
  tasks:
    - name: add ipv4 dhcp fixed address
      nios_fixed_address:
        name: ipv4_fixed
        ipaddr: '{{ ipaddr | mandatory }}'
        mac: '{{ mac | mandatory }}'
        network: '{{ network | mandatory }}'
        network_view: '{{ network_view | mandatory }}'
        comment: '{{ comment | default(omit) }}'
        state: present
        provider:
          host: 172.17.20.50
          username: admin
          password: infoblox
      connection: local
      when: state == "present"
      
    - name: delete ipv4 dhcp fixed address
      nios_fixed_address:
        name: ipv4_fixed
        ipaddr: '{{ ipaddr | mandatory }}'
        mac: '{{ mac | mandatory }}'
        network: '{{ network | mandatory }}'
        network_view: '{{ network_view | mandatory }}'
        comment: '{{ comment | default(omit) }}'
        state: absent
        provider:
          host: 172.17.20.50
          username: admin
          password: infoblox
      connection: local
      when: state == "absent"
