---

- name: Export Endpoint Identity Groups
  hosts: localhost
  vars:
    ansible_host_key_checking: false
  gather_facts: false
  tasks:
    - name: make REST call
      uri:
        url: https://{{ host }}:9060/ers/config/endpointgroup
        user: '{{ username }}'
        password: '{{ password }}'
        method: GET
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        status_code: 200
        headers:
          Content-Type: application/json
          Accept: application/json
      register: output
    
    - debug:
        var: output.json.resources
    
    - name: Copy output to remote location
      ansible.builtin.copy:
        content: output
        dest: \\172.17.20.124\home\Farbod\"{{lookup('pipe','date +%Y-%m-%d')}}".json
      
    
