---

- name: Add Endpoint Identity Groups to Cisco ISE
  hosts: localhost
  vars:
    ansible_host_key_checking: false
  gather_facts: false
  tasks:
    - name: make REST call
      uri:
        url: https://{{ host }}:9060/ers/config/endpointgroup
        user: '{{ username }}'
        password: '{{ password }}'
        method: POST
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        status_code: 201
        headers:
          Content-Type: application/json
          Accept: application/json
        body: '{"EndPointGroup":{"id":"511","name":"AWXTEST","description":"description","systemDefined":false}}'
               
        
