---

- name: Add Endpoint Identity Groups to Cisco ISE
  hosts: 172.17.20.151
  vars:
    ansible_host_key_checking: false
  gather_facts: false
  tasks:
    - name: make REST call
      uri:
        url: https://172.17.20.151:9060/ers/config/endpointgroup
        user: admin
        password: Cisco123!
        method: POST
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        headers:
          Content-Type: application/json
          Accept: application/json
        body: '{"EndPointGroup":{"id":"id","name":"name","description":"description","systemDefined":true}}'
               
        
